default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){5} %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager